version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.1.0
  shellcheck: circleci/shellcheck@3.2.0

filters: &filters
  tags:
    only: /.*/

parameters:
  test:
    type: string
    default: ""
    description: "Whether this is test pipeline."
  test_workflow_id:
    type: string
    default: ""
    description: "The parameter that contains the CircleCI workflow ID."

commands:
  generate-config:
    steps:
      - run:
          name: Generate config from envsubst template(s)
          command: |
            export ORB_GITHUB_ORG="${CIRCLE_PROJECT_USERNAME}"
            export ORB_NAMESPACE="$(echo "${ORB_GITHUB_ORG}" | tr [[:upper:]] [[:lower:]])"
            for tmpl in .circleci/*.yml.envsubst
            do
              circleci env subst <"${tmpl}" >"${tmpl%.envsubst}"
            done

jobs:
  success:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Success
          command: echo "Success!"

workflows:
  lint-pack:
    when:
      equal: ["", << pipeline.parameters.test >>]
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          config_path: .circleci/test-deploy.yml
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: circleback
          requires:
            [orb-tools/lint, orb-tools/pack, orb-tools/review, shellcheck/check]
          filters: *filters
          pre-steps:
            - generate-config

  test_wait:
    when:
      equal: ["wait", << pipeline.parameters.test >>]
    jobs:
      - success:
          filters: *filters

  test-approve:
    when:
      equal: ["approve", << pipeline.parameters.test >>]
    jobs:
      - orb-tools/pack:
          filters: *filters
      - orb-tools/continue:
          config_path: .circleci/test-approve.yml
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: circleback
          requires: [orb-tools/pack]
          filters: *filters
          pre-steps:
            - generate-config
